version: '3.9'
services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: ./Dockerfile
    restart: always
    command: npm run start
    volumes:
      - /app/node_modules
      - ./client:/app/
    ports:
      - 3000:3000
    environment:
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true
    networks:
      - ticket

  auth:
    container_name: auth
    build:
      context: ./auth
      dockerfile: ./Dockerfile
    restart: always
    command: npm run start
    volumes:
      - /app/node_modules
      - ./auth:/app/
    ports:
      - 5001:5001
    networks:
      - ticket

networks:
  ticket:
    driver: bridge
