import type { AppProps } from 'next/app';
import Head from 'next/head';

import '@src/styles/globals.scss';

import { IPageContext } from '@src/context/page.context';
import { AppContextProvider } from '@src/context/app.context';

const App = ({ Component, pageProps }: AppProps<IPageContext>): JSX.Element => {
  let props: any;
  if (pageProps.data) {
    props = pageProps.data;
  }

  return (
    <>
      <Head>
        <title>{pageProps?.pageName || 'App page'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppContextProvider {...props}>
        <Component {...pageProps} />
      </AppContextProvider>
    </>
  );
};

// App.getInitialProps = async appCtx => {
//   try {
//     let pageProps = {};
//     if (appCtx.Component.getInitialProps) {
//       pageProps = await appCtx.Component.getInitialProps(appCtx.ctx);
//     }
//     return { pageProps };
//   } catch (e) {
//     if (e instanceof Error) return { err: e.message };
//   }
// };

export default App;
