import Head from 'next/head';

import { withLayout } from '@src/layout/Layout';

const Home = (): JSX.Element => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>app home</h1>
    </>
  );
};

Home.getInitialProps = async ctx => {
  console.dir(ctx);
  return { ctx };
};

export default withLayout(Home);
