import Head from 'next/head';
import Link from 'next/link';
import { NextPage } from 'next';

import { withPageLayout } from '@src/layout/Layout';
import { IPageContext } from '@src/context/page.context';
import { FirstLevelMenu, Ticket, FnProps } from '@src/interfaces';
import { API } from '@src/helpers/api';

interface HomePageProps extends IPageContext, Record<string, unknown> {
  tickets?: Ticket[];
}

const HomePage: NextPage<HomePageProps> = ({ pageName, tickets }): JSX.Element => {
  const ticketList = tickets?.map(ticket => {
    return (
      <tr key={ticket.id}>
        <td>{ticket.title}</td>
        <td>{ticket.price}</td>
        <td>
          <Link href={`/tickets/[ticketId]`} as={`/tickets/${ticket.id}`} className="btn btn-primary">
            View
          </Link>
        </td>
      </tr>
    );
  });

  return (
    <>
      <Head>
        <title>{pageName}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {tickets && (
        <div className="container">
          <h1>Tickets</h1>

          <table className="table">
            <thead>
              <tr>
                <th>Title</th>
                <th>Price</th>
                <th>Link</th>
              </tr>
            </thead>
            <tbody>{ticketList}</tbody>
          </table>
        </div>
      )}
    </>
  );
};

const HomePageInitProps: FnProps<HomePageProps> = async (_ctx, client, payload): Promise<HomePageProps> => {
  try {
    if (!client) throw new Error('Client not found');

    const tickets = await client.get<{ data: Ticket[] }>(API.tickets.getTickets);

    return { pageName: FirstLevelMenu.Home, ...payload, tickets: tickets.data?.data };
  } catch (e) {
    if (e instanceof Error) return { pageName: FirstLevelMenu.Home, err: e.message };
    return { pageName: FirstLevelMenu.Home, err: e };
  }
};

export default withPageLayout<HomePageProps>(HomePage, HomePageInitProps);
