import Head from 'next/head';
import { NextPage, NextPageContext } from 'next';

import { withPageLayout } from '@src/layout/Layout';
import { IPageContext } from '@src/context/page.context';
import { FirstLevelMenu } from '@src/interfaces';
import { API } from '@src/helpers/api';
import { ClientAxios } from '@src/api/build-client';

interface HomePageProps extends IPageContext, Record<string, unknown> {}

const HomePage: NextPage<HomePageProps> = (props): JSX.Element => {
  return (
    <>
      <Head>
        <title>{props.pageName}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>{props.pageName}</h1>
    </>
  );
};

const HomePageInitProps = async (ctx: NextPageContext): Promise<HomePageProps> => {
  try {
    const client = new ClientAxios(ctx).init();
    const { data } = await client.get<{ data: object }>(API.auth.currentuser);

    return { pageName: FirstLevelMenu.Home, ...data };
  } catch (e) {
    if (e instanceof Error) return { pageName: FirstLevelMenu.Home, err: e.message };
    return { pageName: FirstLevelMenu.Home, err: e };
  }
};

export default withPageLayout<HomePageProps>(HomePage, HomePageInitProps);
