---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats:2.9.16-alpine
          args:
            - '-c'
            - '/etc/nats/nats.conf'
            # - '-auth=/etc/nats/auth.conf'
          resources:
            requests:
              memory: '400Mi'
              cpu: '500m'
            limits:
              memory: '400Mi'
              cpu: '500m'
          ports:
            - containerPort: 4222
          volumeMounts:
            - name: nats-config-volume
              mountPath: /etc/nats
            # - name: nats-auth-volume
            #   mountPath: /etc/nats
            #   readOnly: true
      volumes:
        - name: nats-config-volume
          configMap:
            name: nats-config
            items:
              - key: nats.conf
                path: nats.conf
        # - name: nats-auth-volume
        #   configMap:
        #     name: nats-auth-config
        #     items:
        #       - key: nats-auth.conf
        #         path: nats-auth.conf
---
apiVersion: v1
kind: Service
metadata:
  name: nats-srv
spec:
  selector:
    app: nats
  ports:
    - name: client
      protocol: TCP
      port: 4222
      targetPort: 4222
    - name: cluster
      protocol: TCP
      port: 6222
      targetPort: 6222
    - name: monitor
      protocol: TCP
      port: 8222
      targetPort: 8222
    - name: metrics
      protocol: TCP
      port: 7777
      targetPort: 7777
    - name: leafnodes
      protocol: TCP
      port: 7422
      targetPort: 7422
    - name: gateways
      protocol: TCP
      port: 7522
      targetPort: 7522
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nats-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nats-depl
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
