---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-auth-config
data:
  nats-auth.conf: |
    user username {
      password: password
      permissions {
        publish {
          allow: ">"
        }
        subscribe {
          allow: ">"
        }
      }
    }
