apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: bipus/auth
          # resources:
          #   requests:
          #     ephemeral-storage: '1Gi'
          #     memory: '400Mi'
          #     cpu: '500m'
          #   limits:
          #     ephemeral-storage: '2Gi'
          #     memory: '400Mi'
          #     cpu: '500m'
          env:
            - name: JWT_SALT
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SALT
            - name: MONGO_URL
              value: 'mongodb://auth-mongo-srv:27017/auth'
            - name: SRV_NAME
              value: 'AUTH'

---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: auth-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth-depl
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50
