apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: bipus/expiration
          # resources:
          #   requests:
          #     ephemeral-storage: '1Gi'
          #     memory: '400Mi'
          #     cpu: '500m'
          #   limits:
          #     ephemeral-storage: '2Gi'
          #     memory: '400Mi'
          #     cpu: '500m'
          env:
            - name: SRV_NAME
              value: 'EXPIRATION'
            - name: NATS_CLUSTER_ID
              value: 'ticketing'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: REDIS_HOST
              value: 'expiration-redis-srv'

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: expiration-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: expiration-depl
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50
