apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: bipus/expiration
          env:
            - name: SRV_NAME
              value: 'EXPIRATION'
            - name: NATS_CLUSTER_ID
              value: 'ticketing'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
---
apiVersion: v1
kind: Service
metadata:
  name: expiration-srv
spec:
  selector:
    app: expiration
  ports:
    - name: expiration
      protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: expiration-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: expiration-depl
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50
