apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: bipus/tickets
          resources:
            requests:
              ephemeral-storage: '1Gi'
              memory: '400Mi'
              cpu: '500m'
            limits:
              ephemeral-storage: '2Gi'
              memory: '400Mi'
              cpu: '500m'
          env:
            - name: JWT_SALT
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SALT
            - name: MONGO_URL
              value: 'mongodb://tickets-mongo-srv:27017/tickets'
            - name: SRV_NAME
              value: 'TICKETS'
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: tickets-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tickets-depl
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50
# ---
# apiVersion: policy/v1beta1
# kind: PodDisruptionBudget
# metadata:
#   name: tickets-pdb
# spec:
#   maxUnavailable: 50%
#   selector:
#     matchLabels:
#       app: tickets-app
