apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  storageClassName: ''
  accessModes:
    - ReadWriteOnce
  volumeName: pv
  resources:
    requests:
      storage: 1Gi
# Persistent Volume Claims (PVC): are Kubernetes objects that act as requests for storage.
# Kubernetes looks for a PV from which space can be claimed and assigned for a PVC.
# PVC works only if you have dynamic volume provisioning enabled in the Kubernetes cluster.
