name: deploy-auth

on:
  push:
    branches:
      - main
    paths:
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      DOCKER_USERNAME: ${{ secrets.secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.secrets.DOCKER_PASSWORD }}

    steps:
      - uses: actions/checkout@v2
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: cd auth && docker build -t bipus/auth .
      - run: docker push bipus/auth
      # - uses: digitalocean/action-doctl@v2
      #   with:
      #     token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      # - run: doctl kubernetes cluster kubeconfig save ticketing
      # - run: kubectl rollout restart deployment auth-depl
