name: deploy-tickets

on:
  push:
    branches:
      - main
    paths:
      - 'tickets/**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: secrets
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker login
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build image
        run: cd tickets && docker build -t ${{ secrets.DOCKER_USERNAME }}/tickets:latest .

      - name: Docker push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/tickets

      # - uses: digitalocean/action-doctl@v2
      #   with:
      #     token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      # - run: doctl kubernetes cluster kubeconfig save ticketing
      # - run: kubectl rollout restart deployment tickets-depl
